cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    adminuser:
      email: adminuser@gmail.com
      failed_login_attempts: 0
      logged_in: true
      name: adminuser
      password: $2b$12$b30v4eTdx0fPCLWm/qcePOPSV7ahx1eZDZgBsHtTfrJSTbVsX.I7a
      role: admin
    readonly:
      email: readonly@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: readonly
      password: $2b$12$MXwmS1rIjOFOtnrnaBJKOOHS0IW/wFZ30cBF8p.j9yIQGDOJA3uwy
      role: user
preauthorized:
  emails:
  - readonly@gmail.com
  - adminuser@gmail.com
